name: edgar-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - typer[all]==0.6.1
  - uvicorn==0.18.2
  - fastapi==0.78.0
  - pandas==1.4.3
  - lxml==4.9.1
  - pyyaml==6.0
  - jupyterlab>=3.4.3
  - rise==5.7.1
  - pytest
  - black

