from setuptools import setup, find_packages

setup(
    name="edgar2data",
    version="0.2.0",
    author="Will Thompson",
    author_email="wkt@northwestern.edu",
    maintainer="Will Thompson",
    maintainer_email="wkt@northwestern.edu",
    description="Code for parsing EDGAR filings",
    url="https://github.com/rs-kellogg/edgar2data",
    packages=find_packages(include=["edgar", "edgar.*"]),
    package_data={"edgar": ["templates/*.j2"]},
    include_package_data=True,
    install_requires=[
        "lxml",
        "rich",
        "pandas",
        "pyyaml",
        "typer[all]",
        "typer-cli",
        "colorama",
        "shellingham",
        "click-spinner",
        "tabulate",
        "tqdm",
        "fastapi",
        "uvicorn",
        "icecream",
        "spacy>=3",
    ],
    extras_require={"interactive": ["jupyter", "rise"]},
    entry_points={"console_scripts": ["edgar2data=edgar.cli:app"]},
    # setup_requires=["black", "yappi"],
    tests_require=["pytest"],
)
